### PR TITLE
Create binary_sensor.it.json

### PR DESCRIPTION
**Pull request by riddik14**
new language italian

### CODE REVIEW

**Comment by riddik14** [comment]
new language italian

**Review by Limych — CHANGES_REQUESTED** [review]
Please try to put the same meaning in the shortest possible phrases. Such long text lengths can be inconvenient for users.

I know Italians love to talk. But still this is not the right place ... :smiley:

**Comment by riddik14** [comment]
cosi per, con il testo esteso per far arrivare una notifica basta mandare lo stato del binary_sensor

**Comment by Limych** [comment]
Ti non parlo italiano, scusi.

It is customary here to communicate in English.  If you do not know it, Google Translate may be useful for you.

**Pull request closed without merging**
