### PR TITLE
Added German translation

### PR DESCRIPTION
**Pull request by eopo**
## Proposed change
Added a German language file for human readable output of the sensor state

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (which adds functionality to an this integration) (kind of)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

```yaml
# Example configuration.yaml
binary_sensor:
  - platform: car_wash
    weather: weather.dwd_weather_musterstadt
    name: Fahrzeugpflege
```

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] The code has been formatted using Black (`black --fast custom_components`)

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated to README.md

### CODE REVIEW

**Review by Limych — CHANGES_REQUESTED** [review]
Thank you for your hard work translating this sensor into German.

The only thing that confuses me is the length of the texts. For some users, this may cause the sensor to be poorly displayed in the interface.

Please try to formulate the same thoughts with a smaller volume of text.

Perhaps this issue will be useful to you: https://github.com/Limych/ha-car_wash/issues/27

**Review by LuckyTriple7 — APPROVED** [review]

**Comment by LuckyTriple7** [comment]
Translation is good, Thank you very much.
German is not an easy language, Shorter Discriptions can be:
  "off": "Nicht lohnend",
  "on": "  "off": "Lohnenswert",

or
  "off": "Nicht empfehlenswert",
  "on": "  "off": "Empfehlenswert",

**Comment by Limych** [comment]
@LuckyTriple7 Thank you for your help.

@eopo Please decide among yourself which translation is better.  After that, it is enough to make a new commit to the branch from which this PR is made.  New edits will be automatically added to this PR.

**Comment by eopo** [comment]
> @LuckyTriple7 Thank you for your help.
> 
> @eopo Please decide among yourself which translation is better. After that, it is enough to make a new commit to the branch from which this PR is made. New edits will be automatically added to this PR.

Didn't see your annotations until now, quickly changed.

**Comment by Limych** [comment]
Thank you 💓

**Pull request merged**
